name: Prerelease Build

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+rc[0-9]+"]
    branches: ["*"]

jobs:
  pypi_deploy:
    name: Deploy to PyPI
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v') }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install build
          pip install twine

      - name: Build Package
        run: |
          python -m build

      - name: Check Package
        run: |
          twine check dist/* --strict

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/* --verbose